# Generated by Django 5.2.8 on 2025-11-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=200)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='The Email')),
                ('Phone', models.CharField(blank=True, max_length=16, null=True)),
                ('Message', models.TextField()),
            ],
        ),
    ]
